"""PROPOSE: publish exactly the package that a person approved, then read the result back."""

from collections.abc import Callable
from datetime import UTC, datetime
from hashlib import sha256
import os
from pathlib import Path
import shutil
import subprocess
import tempfile
from typing import NamedTuple

from pydantic import BaseModel

from maga.schemas import Verdict


class Destination(NamedTuple):
    repo: Path  # the Git repository that receives the branch
    target: Path  # where the package goes, relative to `repo`


class PrService(NamedTuple):
    open_pr: Callable[[Path, str, str, str], str]  # repo, branch, title, body -> the PR URL
    read_back: Callable[[Path, str], str]  # repo, PR URL -> the head commit of the PR


_GIT_LOCATION = {
    "GIT_DIR",
    "GIT_WORK_TREE",
    "GIT_INDEX_FILE",
    "GIT_COMMON_DIR",
    "GIT_OBJECT_DIRECTORY",
    "GIT_ALTERNATE_OBJECT_DIRECTORIES",
    "GIT_PREFIX",
}


class PackageApproval(BaseModel):
    """The record that binds one human approval to one candidate and one package content."""

    candidate_id: str
    approved: bool
    package_sha256: str
    timestamp: datetime


class PublishError(Exception):
    """The package was not published, and the message says why."""


def package_hash(staged: Path) -> str:
    """One hash over every file below `staged`: its relative path and its bytes."""
    digest = sha256()
    for path in sorted(p for p in staged.rglob("*") if p.is_file()):
        digest.update(path.relative_to(staged).as_posix().encode() + b"\0")
        digest.update(path.read_bytes() + b"\0")
    return digest.hexdigest()


def approve_package(state: Path, candidate_id: str, staged: Path) -> Path:
    """Record that a person approved exactly this package content."""
    approval = state / "approvals" / f"{candidate_id}_package.json"
    approval.parent.mkdir(parents=True, exist_ok=True)
    record = PackageApproval(
        candidate_id=candidate_id,
        approved=True,
        package_sha256=package_hash(staged),
        timestamp=datetime.now(UTC),
    )
    approval.write_text(record.model_dump_json(indent=2))
    return approval


def _require(state: Path, candidate_id: str, staged: Path) -> str:
    """The package hash, only with a Gate 2 pass and a human approval for this exact content."""
    current = package_hash(staged)
    verdict_file = state / "verification" / f"{candidate_id}_gate2_verdict.json"
    approval_file = state / "approvals" / f"{candidate_id}_package.json"
    if not verdict_file.exists():
        message = f"no Gate 2 verdict for {candidate_id}"
        raise PublishError(message)
    verdict = Verdict.model_validate_json(verdict_file.read_bytes())
    if verdict.outcome != "pass" or verdict.test_results.get("package_sha256") != current:
        message = f"no Gate 2 pass for this exact package of {candidate_id}"
        raise PublishError(message)
    approval = (
        PackageApproval.model_validate_json(approval_file.read_bytes())
        if approval_file.exists()
        else None
    )
    if (
        approval is None
        or not approval.approved
        or approval.candidate_id != candidate_id
        or approval.package_sha256 != current
    ):
        message = f"no human approval for this exact package of {candidate_id}"
        raise PublishError(message)
    return current


def git(repo: Path, *args: str) -> str:
    # A Git hook exports the location of its own repository. `cwd` alone must select the repository.
    env = {key: value for key, value in os.environ.items() if key not in _GIT_LOCATION}
    done = subprocess.run(
        ["git", *args], cwd=repo, env=env, capture_output=True, text=True, check=False
    )
    if done.returncode != 0:
        message = f"git {' '.join(args)} failed: {done.stderr.strip()}"
        raise PublishError(message)
    return done.stdout.strip()


def publish(
    state: Path, candidate_id: str, staged: Path, destination: Destination, service: PrService
) -> str:
    """Commit the approved files at the destination, push, open a PR, and read it back."""
    repo, target = destination
    approved_hash = _require(state, candidate_id, staged)
    branch = f"maga/{candidate_id}"
    worktree = Path(tempfile.mkdtemp(prefix="maga_propose_")) / "repo"
    git(repo, "worktree", "add", "-b", branch, str(worktree), "HEAD")
    try:
        # The approved files and nothing else: never `git add -A`.
        files = sorted(p.relative_to(staged) for p in staged.rglob("*") if p.is_file())
        for file in files:
            (worktree / target / file).parent.mkdir(parents=True, exist_ok=True)
            shutil.copy(staged / file, worktree / target / file)
        git(worktree, "add", "--", *[str(target / file) for file in files])
        git(worktree, "commit", "-m", f"feat: add the {target.name} skill generated by MAGA")
        pushed = git(worktree, "rev-parse", "HEAD")
        git(worktree, "push", "-u", "origin", branch)
        body = (
            "## Problem\n\nAgents repeat this procedure by hand in each session.\n\n"
            "## Change\n\nA generated script, its skill, and its acceptance tests.\n\n"
            f"## Verification\n\nGate 1 and Gate 2 passed for package `{approved_hash}`.\n"
        )
        url = service.open_pr(
            worktree, branch, f"feat: add the {target.name} skill generated by MAGA", body
        )
        head = service.read_back(worktree, url)
    finally:
        git(repo, "worktree", "remove", "--force", str(worktree))
    if head != pushed:
        message = f"read-back mismatch: {url} has head {head}, but the pushed commit is {pushed}"
        raise PublishError(message)
    return url


def _gh(repo: Path, *args: str) -> str:
    done = subprocess.run(["gh", *args], cwd=repo, capture_output=True, text=True, check=False)
    if done.returncode != 0:
        message = f"gh {args[0]} {args[1]} failed: {done.stderr.strip()}"
        raise PublishError(message)
    return done.stdout.strip()


def _open_pr(repo: Path, branch: str, title: str, body: str) -> str:
    return _gh(repo, "pr", "create", "--head", branch, "--title", title, "--body", body)


def _read_back(repo: Path, url: str) -> str:
    return _gh(repo, "pr", "view", url, "--json", "headRefOid", "--jq", ".headRefOid")


GITHUB = PrService(_open_pr, _read_back)
